version: '2'
services: 
  postgres:
    image: "postgres:9.4"
    environment: 
      POSTGRES_PASSWORD: api_admin
      POSTGRES_USER: postgre_user
   web:
      build: .
      ports:
       - "80:7777"
      volumes:
       - .:/usr/src/app
      depends_on:
       - postgres
      command: ["./wait_for_it.sh"", "postgres:5432", "npm", "start"]